#This code is generated by LLM
import os
import cv2
import numpy as np
from ultralytics import YOLO


def load_or_export_model(device=0):
    model_path = "../models/yolo11n.engine"
    pt_path = "../models/yolo11n.pt"

    if os.path.exists(model_path):
        try:
            test_model = YOLO(model_path, task='detect')
            dummy_frame = np.zeros((640, 640, 3), dtype=np.uint8)
            test_model.predict(dummy_frame, imgsz=640, device=device, verbose=False)
            return test_model
        except Exception as e:
            os.remove(model_path)

    pt_model = YOLO(pt_path)
    pt_model.export(format='engine', imgsz=640, device=device, half=True, simplify=True)
    return YOLO(model_path, task='detect')


def generate_heatmap(video_path, output_path, device=0):
    model = load_or_export_model(device=device)
    cap = cv2.VideoCapture(video_path)

    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = cap.get(cv2.CAP_PROP_FPS)

    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, fps, (width, height))

    print("正在處理影片並生成實時置信度熱力圖...")

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # 推理
        results = model.predict(frame, imgsz=640, device=device, verbose=False)

        # 每一幀都創建全新的熱力圖層（無拖尾的核心）
        current_conf_map = np.zeros((height, width), dtype=np.float32)

        # 建立一個用於寫字的圖層
        text_layer = frame.copy()

        for result in results:
            for box in result.boxes:
                # 取得坐標與置信度
                x1, y1, x2, y2 = map(int, box.xyxy[0].cpu().numpy())
                conf = float(box.conf[0])

                # 在熱力圖層填充置信度
                current_conf_map[y1:y2, x1:x2] = conf

                # --- 添加置信度數字顯示 ---
                label = f"{conf:.2f}"
                # 繪製文字背景（可選，增加可讀性）
                cv2.putText(text_layer, label, (x1, y1 - 10),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 255), 2)

        # 使用高斯模糊讓球的熱力點變圓滑（調試時更好看）
        if np.max(current_conf_map) > 0:
            current_conf_map = cv2.GaussianBlur(current_conf_map, (25, 25), 0)

        # 歸一化並應用顏色
        viz_heatmap = (current_conf_map * 255).astype(np.uint8)
        color_heatmap = cv2.applyColorMap(viz_heatmap, cv2.COLORMAP_JET)

        # 將熱力圖疊加到帶有文字的圖層上
        # alpha=0.6 是原圖權重，beta=0.4 是熱力圖權重
        final_frame = cv2.addWeighted(text_layer, 0.7, color_heatmap, 0.3, 0)

        out.write(final_frame)

        # 如果環境支持 GUI 則顯示
        # cv2.imshow("Debug Heatmap", final_frame)
        # if cv2.waitKey(1) & 0xFF == ord('q'): break

    cap.release()
    out.release()
    print(f"處理完成！輸出文件：{output_path}")

if __name__ == "__main__":
    generate_heatmap("../input_videos/input_video.mp4", "../output_videos/output_video_heat.mp4", device=0)